// Source of truth: 08_ERROR_STATUS_CATALOG.md §4
// Both backend (throws/returns these) and frontend (switches on these) import from here.

export const ErrorCode = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  KYC_NOT_APPROVED: "KYC_NOT_APPROVED",
  ACCOUNT_TYPE_NOT_FOUND: "ACCOUNT_TYPE_NOT_FOUND",
  ACCOUNT_TYPE_INACTIVE: "ACCOUNT_TYPE_INACTIVE",
  INVALID_LEVERAGE: "INVALID_LEVERAGE",
  ACCOUNT_LIMIT_REACHED: "ACCOUNT_LIMIT_REACHED",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_NOT_OWNED: "WALLET_NOT_OWNED",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  DESTINATION_NOT_FOUND: "DESTINATION_NOT_FOUND",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  CONFIRMATION_INVALIDATED: "CONFIRMATION_INVALIDATED",
  OTP_INVALID: "OTP_INVALID",
  OTP_REQUIRED: "OTP_REQUIRED",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  INTEGRATION_TIMEOUT: "INTEGRATION_TIMEOUT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  UNKNOWN_RESULT: "UNKNOWN_RESULT",
  KNOWLEDGE_NOT_FOUND: "KNOWLEDGE_NOT_FOUND",
  SUPPORT_HANDOFF_REQUIRED: "SUPPORT_HANDOFF_REQUIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// Common error envelope shape — matches 05_API_CONTRACT.md §14
export interface ApiError {
  error: {
    code: ErrorCode;
    message: string;
    request_id?: string;
  };
}

export interface HttpError extends Error {
  status?: number;
  code?: ErrorCode;
}
